
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROCEDURE = 9;
  public static final int ELSE = 29;
  public static final int RELACIONAIS = 26;
  public static final int OR = 2;
  public static final int THEN = 13;
  public static final int PONTO = 20;
  public static final int WHILE = 14;
  public static final int ABREPAR = 23;
  public static final int NOT = 16;
  public static final int END = 11;
  public static final int TRUE = 30;
  public static final int IF = 12;
  public static final int PONTOVIRG = 21;
  public static final int ID = 17;
  public static final int PROGRAM = 4;
  public static final int BEGIN = 10;
  public static final int DO = 15;
  public static final int ATRIBUICAO = 25;
  public static final int BOOLEAN = 8;
  public static final int INTEIROS = 18;
  public static final int DOISPONTOS = 22;
  public static final int EOF = 0;
  public static final int MULTIPLICATIVOS = 28;
  public static final int FALSE = 31;
  public static final int VAZIO = 3;
  public static final int error = 1;
  public static final int FECHAPAR = 24;
  public static final int ADITIVOS = 27;
  public static final int INTEGER = 6;
  public static final int REAL = 7;
  public static final int REAIS = 19;
  public static final int VAR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OR",
  "VAZIO",
  "PROGRAM",
  "VAR",
  "INTEGER",
  "REAL",
  "BOOLEAN",
  "PROCEDURE",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "WHILE",
  "DO",
  "NOT",
  "ID",
  "INTEIROS",
  "REAIS",
  "PONTO",
  "PONTOVIRG",
  "DOISPONTOS",
  "ABREPAR",
  "FECHAPAR",
  "ATRIBUICAO",
  "RELACIONAIS",
  "ADITIVOS",
  "MULTIPLICATIVOS",
  "ELSE",
  "TRUE",
  "FALSE"
  };
}

